#!/usr/bin/env node
/**
 * Verifies every commit in a range carries a DCO `Signed-off-by` trailer, mirroring the
 * local commit-msg hook so the rule survives `--no-verify`.
 *
 * Usage: node scripts/check-dco.mjs <base-sha> <head-sha>
 */
import { execFileSync } from "node:child_process";

const [base, head] = process.argv.slice(2);

if (!base || !head) {
  console.error("Usage: node scripts/check-dco.mjs <base-sha> <head-sha>");
  process.exit(2);
}

// git expands %x1e itself; the separator cannot be passed as a raw byte in an argv entry.
const SEPARATOR = "\u001e";
const SIGN_OFF = /^Signed-off-by: .+ <.+@.+>$/im;

// Merge commits are generated by GitHub, not authored by a contributor, so they are exempt.
const log = (() => {
  try {
    return execFileSync(
      "git",
      ["log", "--no-merges", "--format=%H%n%s%n%b%x1e", `${base}..${head}`],
      { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
    );
  } catch (error) {
    console.error(`✖ Could not read commit range ${base}..${head}`);
    console.error(String(error.stderr ?? error.message).trim());
    process.exit(2);
  }
})();

const commits = log
  .split(SEPARATOR)
  .map((entry) => entry.trim())
  .filter(Boolean)
  .map((entry) => {
    const [sha, subject, ...rest] = entry.split("\n");
    return { sha, subject, body: rest.join("\n") };
  });

const missing = commits.filter(
  ({ subject, body }) => !SIGN_OFF.test(`${subject}\n${body}`),
);

if (missing.length > 0) {
  console.error("✖ Commits missing a DCO Signed-off-by trailer:\n");
  for (const { sha, subject } of missing) {
    console.error(`  ${sha.slice(0, 8)} ${subject}`);
  }
  console.error("\nSign off with `git commit -s`, or amend existing commits:");
  console.error(`  git rebase --signoff ${base}\n`);
  console.error("See CONTRIBUTING.md and https://developercertificate.org/");
  process.exit(1);
}

console.log(`✔ ${commits.length} commit(s) signed off.`);
